### PR TITLE
🐛 throttle concurrent file reads to prevent exceptions when there are many files

### LINKED ISSUE #1: calling `find` throws if there are a large number of records
calling `store.find()` will throw if there are many records

```
[Error: EMFILE: too many open files, open '[redacted]'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '[redacted]',
  meta: {},
  payload: null
}
```

it's almost certainly caused by the [unbounded `fs.readFile()`](https://github.com/fortunejs/fortune-fs/blob/master/index.js#L89)

### PR DESCRIPTION
**Pull request by ctcpip**
resolves #1 

also updated dependencies

edit: also added CI workflow

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -85,27 +82,38 @@ module.exports = function (Adapter) {
...
-    ).then(function (files) {
-      return Promise.all(map(files, function (file) {
-        return new Promise(function (resolve, reject) {
-          var filePath = path.join(dbPath, type, '' + file)
+    ).then(async function (files) {
+      const allThePromises = []
+      const concurrentReads = 256
+      let promiseCount = 0
+
+      while(promiseCount < files.length) {
```
Comment (gr0uch) [inline index.js]: hmm, although this works, what it's actually doing is processing batches of 256 files at once. let's say there are 1024 files to read. it will execute in order:
- 0-256
- 256-512
- 512-768
- 768-1024

might be more efficient to process a maximum of 256 files at once, [for example](https://gist.github.com/jcouyang/632709f30e12a7879a73e9e132c0d56b).

---

side note: I read that "on OS X, the default is 256", but unsure about linux distros. might be safer to go under this default limit, like 128 perhaps, because any other open file handles will cause it to go above the limit.

**Review by gr0uch — APPROVED** [review]

File: index.js (hunk 1 above)
Comment (ctcpip) [reply index.js]: this is a good point.  I was trying to make minimal changes to the existing code, but I have done this sort of thing before, where the upper bound is defined, and you just let rip until it's full, then push a new one on each time one comes off.

I agree `256` is too high.  there is no perfect answer because the size of the records makes a big difference, but without benchmarking, I think we just pick something reasonable.  `32` is probably a good number but I will run a few benchmarks on my data

Comment (ctcpip) [reply index.js]: some interesting results:

benchmark with 124732 records (files)

| concurrent read limit | execution time (ms) |
| --- | --- |
|32 | 44872|
|64 | 22324|
|128 | 11163|
|256 | 9616|
|512 | 6993|
|1024 | 6298|
|2048 | 6376|
|4096 | 6602|
|8192 | 6497|
|32768 | 6453|
|65536 | 6599|
|131072 | Error: EMFILE: too many open files|

conclusion:

- there's clearly a perf cliff beyond ~512
- this seems to suggest the sweet spot is `1024`
- surprisingly, I didn't get the open files error until specifying 131072 concurrent requests

File: index.js [hunk 2]
```diff
@@ -85,27 +87,44 @@ module.exports = function (Adapter) {
...
+      const allThePromises = []
+      let readsInFlight = 0
+      const iterator = files[Symbol.iterator]()
 
-          fs.readFile(filePath, function (error, buffer) {
-            var record
+      while (allThePromises.length < files.length) {
+        if(readsInFlight >= concurrentReads) {
+          // back off
+          await pause(10)
```
Comment (gr0uch) [inline index.js]: hmm this can be quite finicky due to some situations where this is sub-optimal:
- reads are super fast and result in idling for the majority of 10ms
- reads take 10ms longer than they should because there's just 1 more file to read

ideally the next promise starts immediately when a previous one is resolved, without relying on assumptions around timing.

there are some good examples in the comments of [this gist](https://gist.github.com/jcouyang/632709f30e12a7879a73e9e132c0d56b) or even a [package](https://www.npmjs.com/package/p-limit) though i'd prefer not to import a package for a trivial amount of code.

Comment (ctcpip) [reply index.js]: alright, I rolled my own, and perf was not as good as the 10ms debounce impl.. a couple seconds slower at between 8 and 9 seconds.  of course, a different dataset may yield different results, but still.

I also gave the gist a shot and it was even worse: nearly 13 seconds

p-limit, however, was faster than all these impls...  just shy of 5.5 seconds consistently. looking at the lib code, it's hard to discern why the perf is better than what I hand-rolled.  perf isn't everything, but I'll continue to experiment with optimizations

I agree with you; I am also loathe to add a dependency for this

Comment (ctcpip) [reply index.js]: well, we're not going to do much better than just setting the sleep to `0` just to get an event loop microtask delay

now some interesting results from benchmarking again:

| concurrent read limit | execution time (ms) |
| --- | --- |
|32 | 10632|
|64 | 7076|
|128 | 6706|
|256 | 6865|
|512 | 6880|
|1024 | 6918|
|2048 | 6972|

we now see the cliff at `128`, and degraded performance past that.  so it looks like the magic number if using the `0` back off is `128`

Comment (ctcpip) [reply index.js]: alright code is updated.  also made it configurable, added tests, and updated the readme.  ✨

Comment (gr0uch) [reply index.js]: interesting... 0 is effectively the same as next tick so i guess that works.
